### ISSUE TITLE
Dataset random invariant ID not unique

### ISSUE THREAD

**Issue by AndyClifton** [peterdougstuart/PCWG#113]
Multiple submissions by the same contributor can have the same `Dataset random invariant ID` in the output excel file (cell C12 in the "submission" sheet). Shouldn't this ID be unique to each excel file?

**Comment by lcameron05** [comment]
Hi Andy,

I am not sure exactly how this is happening and would need visibility on how people are using the tool to be sure. At the moment, the "Dataset random invariant ID" is created by the tool when the Dataset Configuration (and therefore the associated xml file) is first saved. As such, if the user edits an existing dataset configuration to set up other datasets (as opposed to using the "New" button) it would result in the same "Dataset random Invariant ID" being submitted twice.

This ID was implemented as the "Dataset Reference" and "Timeseries Reference" would change if the dataset configuration xml or timeseries data file respectively were changed at all. This could lead to a situation whereby changes immaterial to the data or the analysis (eg - changing a column header) would lead to different references and so an ID tied to the dataset configuration file was felt to be useful. However, given this is being replicated across submissions for presumably different datasets we may need to rethink how this is being handled.

Thanks,
Lee.

**Comment by lcameron05** [comment]
@peterdougstuart instead of a random integer, which can remain the same if people edit the xmls through a text file. Perhaps something related to the time of the files creation might prove more useful? If the time is always the same across different datasets in a submission (see Andy's inital post), we can infer that the contributor is editing a previous xml to create new datasets instead of using "New" in the UI.

**Comment by joekane3** [comment]
what about using the ```hash()``` function? Will give you a unique, but consistent, number for a string. It's used for dictionary keys, for example if you want your class to be able to be a dictionary key you have to define the ```.__hash__(self)``` method.

**Comment by lcameron05** [comment]
Hi Joe,
We use a hash of the contents of the xml to provide an ID that corresponds to the dataset config at the time it is run ([code here](https://github.com/peterdougstuart/PCWG/blob/master/pcwg/core/analysis.py#L21)). The ID we are discussing is a simple 6 digit random number that is created at the time the user first saves the xml through the UI. The intention is different from the hash of the file contents; we do not want it to change every time the user makes a change to the config. It is intended to be a simple check that the user is not submitting the same dataset twice with changes to the analysis/dataset configuration (in this case the hash would change, but the random invariant ID would be the same).

I think the problem is that some users have probably created config xmls for a new dataset by simply editing old ones, and so the ID is the same for different submissions. If the ID inferred the datetime of the file initial creation we could see if that was the case.

**Comment by lcameron05** [comment]
We are no loner actively using this concept as our users are too clever and manually editing the xml configs. As such the dataset invariant random ID is often replicated within a submission.

**Comment by AndyClifton** [comment]
Before we close this, do we actually need to migrate this to a different issue that says "generate unique identifier for each dataset _somehow_ so that contributions can be told apart"?The data processing is muuuch easier when the data each have unique IDs. I could add these at run time I suppose during the analysis process, but it's helpful to have something that goes right the way back to the contributor. On 17 May 2017 17:49, Lee Cameron <notifications@github.com> wrote:We are no loner actively using this concept as our users are too clever and manually editing the xml configs. As such the dataset invariant random ID is often replicated within a submission.

**Comment by lcameron05** [comment]
We will still have a unique identifier for each submission (the full hash of the contents of the configuration) which we can use for this purpose. It is not currently written out in the summary document (`Summary.xls` in the `.zip` file) but is the name of the detailed report for each individual dataset (looks something like `47d623e20be8b22bda6af97bd15b1fad45693a0e` for example) and is given as `Dataset Reference` on the cover sheet of the detailed reports. Is that OK for your purposes? 

I will open a new issue (referencing this one) to ensure we put the dataset unique ID the `Summary.xls` workbook.
