### ISSUE TITLE
GUI errors

### ISSUE THREAD

**Issue by coillarach** [peterdougstuart/PCWG#46]
Clicking on New to create a new dataset gives the error:

AttributeError: 'NoneType' object has no attribute 'link'

Cause is line 572 in pytool.py. If no validation is specified for a field (eg startDate) validation is None.
Can be fixed by a simple condition, but are there any other knock-on issues?

--------------------
Calibration settings fields/buttons are all grayed out

--------------------
Remove column selection buttons from Shear measurements/wind speed height 1 & 2

--------------------
Configuration items needed in GUI for power deviation matrix settings. Without, loading a new configuration fails with:
AttributeError: 'NoneType' object has no attribute 'data'

**Comment by peterdougstuart** [comment]
THIS IS DONE: Remove column selection buttons from Shear measurements/wind speed height 1 & 2

**Comment by peterdougstuart** [comment]
THIS IS DONE: Clicking on New to create a new dataset gives the error: AttributeError: 'NoneType' object has no attribute 'link'

**Comment by peterdougstuart** [comment]
"Calibration settings fields/buttons are all grayed out"

This was actually an attempt to make the UI more intuitive by disabling controls if they are not relevant based on other controls. In this example the hub wind speed mode must have been set to specified so that the calibration settings were not relevant and were disabled.

On reflection I think the above behaviour is a bit confusing so I have changed the UI so that rather than disabling it shows some dynamic messages on the form to indicate which controls contain data which is not required (based on the current selections)

![screen shot 2015-06-16 at 08 07 31](https://cloud.githubusercontent.com/assets/7040056/8177647/cab42030-13fe-11e5-8bce-659cfe054930.png)
.

**Comment by peterdougstuart** [comment]
THIS IS FIXED

Configuration items needed in GUI for power deviation matrix settings. Without, loading a new configuration fails with:
AttributeError: 'NoneType' object has no attribute 'data'

**Comment by peterdougstuart** [comment]
Hi Brian

I not sure what you mean by: "If no validation is specified for a field (eg startDate) validation is None.
Can be fixed by a simple condition, but are there any other knock-on issues?"

Can you give some more details on this e.g. line numbers, error messages, screen shot etc?

Thanks for the feedback.

Peter

**Comment by coillarach** [comment]
Hi Peter

In pcwg_tool.py line 999 creates the Start date field:


self.startDate = self.addEntry(master, "Start Date:", None, self.config.startDate, showHideCommand = self.generalShowHide)


Validation is set to None which causes the error in addEntry at line 572:

validation.link(entry)

This could be fixed by testing for a validation instance:

if validation != None:
        validation.link(entry)

… but maybe every field should have a validation instance even if it is trivial?

Brian

**Comment by peterdougstuart** [comment]
Hi Brian

Thanks I see now. This is fixed i.e. I added an if statement to the addEntry method as suggested:

if validation != None:
        validation.link(entry)

Cheers

Peter

**Comment by peterdougstuart** [comment]
All issues now fixed pending release
