### ISSUE TITLE
Bug: defined nominal wind dist, undefined specified curve

### ISSUE THREAD

**Issue by lcameron05** [peterdougstuart/PCWG#50]
Exception is thrown when wind distribution is defined, but specified curve is not. This occurs because the AEP calculation is attempted when wind distribution is defined, however, a specified curve is required for the analysis.

**Comment by lcameron05** [comment]
Fixed by this commit:

https://github.com/lcameron05/PCWG/commit/e535c5af5e1319132771dd9380ffd7ef0dcc19be

Not yet committed to master.

**Comment by joekane3** [comment]
I actually think it's better to change https://github.com/lcameron05/PCWG/blob/aep_calculation/aep.py#L10 

so that we are not looking at the specified curve every time but the calculation is relative to another curve. For example it could be useful to have an AEP of the AllMeasuredPowerCurve to InnerRangePowerCurve.

**Comment by joekane3** [comment]
@lcameron05  take a look at the changes I've made ( https://github.com/peterdougstuart/PCWG/commit/860dcb22aca4568d603ae246ea9e81729548a8b0 ) and close this if you agree with the solution

**Comment by lcameron05** [comment]
@joekane3 Thanks Joe. I'm happy with this solution.
